import { Router } from 'express';
import { authenticate } from '../middlewares/auth.middleware';
import * as coupleController from '../controllers/couple.controller';

const router = Router();
router.use(authenticate);
router.get('/', coupleController.getMine);
router.post('/request', coupleController.requestBond);
router.post('/respond', coupleController.respond);
router.patch('/', coupleController.updateSpace);
router.post('/sos', coupleController.sendSos);
router.post('/unbind', coupleController.unbind);
router.post('/unbind/request', coupleController.requestUnbind);
router.post('/unbind/respond', coupleController.respondUnbind);
router.get('/items', coupleController.getItems);
router.post('/items', coupleController.createItem);
router.patch('/items/:itemId', coupleController.updateItem);
router.delete('/items/:itemId', coupleController.archiveItem);
router.get('/album/groups', coupleController.getAlbumGroups);
router.post('/album/groups', coupleController.createAlbumGroup);
router.patch('/album/groups/:groupId', coupleController.updateAlbumGroup);
router.delete('/album/groups/:groupId', coupleController.deleteAlbumGroup);
router.post('/album/groups/:groupId/photos', coupleController.addAlbumPhotos);
router.delete('/album/groups/:groupId/photos', coupleController.deleteAlbumPhotos);
export default router;
