ALTER TABLE "PetBond" ADD COLUMN "coins" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "PetBond" ADD COLUMN "biscuits" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "PetBond" ADD COLUMN "activity" TEXT NOT NULL DEFAULT 'idle';
ALTER TABLE "PetBond" ADD COLUMN "activityUntil" TIMESTAMP(3);
ALTER TABLE "PetBond" ADD COLUMN "lastCheckInDay" TEXT NOT NULL DEFAULT '';
