ALTER TABLE "User" ADD COLUMN "presence" TEXT NOT NULL DEFAULT 'online';
ALTER TABLE "PetBond" ADD COLUMN "toys" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PetBond" ADD COLUMN "medicines" INTEGER NOT NULL DEFAULT 0;
